language: node_js
node_js:
    - "8.11.1"
install:
    - npm install
env:
  global:
   - CC_TEST_REPORTER_ID=608827752756cf288300846cf633509fac5750c70568f08f32ba3285e1c8564c

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coveralls

notifications:
  email: false